name: Deploy event description to Eventpop
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://docker.pkg.github.com/dtinth/puppeteer-event-popper/deploy:latest
      with:
        args:
          - description.html
      env:
        EVENT_POPPER_API_KEY: ${{ secrets.EVENT_POPPER_API_KEY }}
        EVENT_POPPER_URL: ${{ secrets.EVENT_POPPER_URL }}
